---

- name: Configure Jenkins server
  hosts: jenkins
  remote_user: ec2-user
  become: true
  tasks:
    - name: install git only if it is not already installed
      yum:
        name=git
        state=present

  roles:
    - geerlingguy.jenkins
    - geerlingguy.repo-epel
    - geerlingguy.git
    - tecris.maven
    - geerlingguy.ansible
