---

- name: Configure Jenkins server
  hosts: tag_ansible_group_jenkins
  #become: true
  tasks:
    - name: install git only if it is not already installed
      yum:
        name=git
        state=present

  roles:
    - geerlingguy.jenkins
    - geerlingguy.repo-epel
    #- geerlingguy.git
    - { role: tecris.maven, maven_version: 3.5.4 }
    - geerlingguy.ansible

- name: Deploy Nexus Server
  hosts: tag_ansible_group_nexus

  roles:
    - geerlingguy.java
    - savoirfairelinux.nexus3-oss

- name: Deploy Sonar Server
  hosts: tag_ansible_group_sonar

  roles:
    - wtanaka.unzip
    - geerlingguy.sonar

- name: On Premises CentOS
  hosts: tag_ansible_group_webserver

  roles:
    - jenkins-keys-config
