---

- name: Configure Jenkins server
  hosts: tag_ansible_group_jenkins
  become: true
  tasks:
    - name: install git only if it is not already installed
      yum:
        name=git
        state=present

  roles:
    - geerlingguy.jenkins
    - geerlingguy.repo-epel
    - geerlingguy.git
    - tecris.maven
    - geerlingguy.ansible

- name: Deploy Nexus Server
hosts: tag_ansible_group_nexus
become: yes

roles:
  - geerlingguy.java
  - savoirfairelinux.nexus3-oss

- name: Deploy Sonar Server
hosts: sonar_server
remote_user: vagrant
become: yes

roles:
  - wtanaka.unzip
  - zanini.sonar

- name: On Premises CentOS
hosts: app_server
remote_user: vagrant
become: yes

roles:
  - jenkins-keys-config
